{
 "title": "HAProxy Prometheus Metrics",
 "tags": [
  "haproxy",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "HAProxy Backend Connection Errors",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "rate(haproxy_backend_connection_errors_total[1m])"
    }
   ]
  },
  {
   "title": "HAProxy Bytes In/Out",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "expr": "rate(haproxy_backend_bytes_in_total[1m])"
    }
   ]
  },
  {
   "title": "HAProxy Current Sessions",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "haproxy_backend_current_sessions"
    }
   ]
  }
 ]
}